- name: Configure MySQL server
  hosts: mysql
  become: yes
  gather_facts: yes

  vars_files:
    - vars.yaml
    - secrets.yaml
  roles:
    - Database

- name: Configure Django backend server
  hosts: django
  become: yes
  gather_facts: yes

  vars_files:
    - vars.yaml
    - secrets.yaml

  roles:
    - Backend
    

- name: Configure Nginx as frontend reverse proxy
  hosts: nginx
  become: yes
  gather_facts: yes

  vars:
    backend_private_ip: "{{ groups['django'][0]}}"

  roles:
    - Frontend
    